/* generated by `basename $0` */

/* -*- Mode: C; tab-width: 8; indent-tabs-mode: nil; c-basic-offset: 8 -*- */
/*
 * This file is part of libosso-abook
 *
 * Copyright (C) 2008 Nokia Corporation. All rights reserved.
 *
 * Contact: Joergen Scheibengruber <jorgen.scheibengruber@nokia.com>
 */

/**
 * SECTION:osso-abook-quarks
 * @short_description: #GQuark<!-- -->s for commonly used strings.
 *
 * This module provides #GQuark<!-- -->s for commonly used strings.
 */

#ifndef __OSSO_ABOOK_QUARKS_H__
#define __OSSO_ABOOK_QUARKS_H__

#include <glib.h>

G_BEGIN_DECLS

#define OSSO_ABOOK_QUARK_VCA_GENDER (osso_abook_quark_vca_gender ())
GQuark osso_abook_quark_vca_gender (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_OSSO_MASTER_UID (osso_abook_quark_vca_osso_master_uid ())
GQuark osso_abook_quark_vca_osso_master_uid (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_TELEPATHY_HANDLE (osso_abook_quark_vca_telepathy_handle ())
GQuark osso_abook_quark_vca_telepathy_handle (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_TELEPATHY_PRESENCE (osso_abook_quark_vca_telepathy_presence ())
GQuark osso_abook_quark_vca_telepathy_presence (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_TELEPATHY_CAPABILITIES (osso_abook_quark_vca_telepathy_capabilities ())
GQuark osso_abook_quark_vca_telepathy_capabilities (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_TELEPATHY_BLOCKED (osso_abook_quark_vca_telepathy_blocked ())
GQuark osso_abook_quark_vca_telepathy_blocked (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_TELEPATHY_SUBSCRIBED (osso_abook_quark_vca_telepathy_subscribed ())
GQuark osso_abook_quark_vca_telepathy_subscribed (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_TELEPATHY_PUBLISHED (osso_abook_quark_vca_telepathy_published ())
GQuark osso_abook_quark_vca_telepathy_published (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCP_OSSO_READONLY (osso_abook_quark_vcp_osso_readonly ())
GQuark osso_abook_quark_vcp_osso_readonly (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCP_OSSO_VALID (osso_abook_quark_vcp_osso_valid ())
GQuark osso_abook_quark_vcp_osso_valid (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCP_OSSO_VARIANTS (osso_abook_quark_vcp_osso_variants ())
GQuark osso_abook_quark_vcp_osso_variants (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_ADR (osso_abook_quark_vca_adr ())
GQuark osso_abook_quark_vca_adr (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_BDAY (osso_abook_quark_vca_bday ())
GQuark osso_abook_quark_vca_bday (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_CALURI (osso_abook_quark_vca_caluri ())
GQuark osso_abook_quark_vca_caluri (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_CATEGORIES (osso_abook_quark_vca_categories ())
GQuark osso_abook_quark_vca_categories (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_EMAIL (osso_abook_quark_vca_email ())
GQuark osso_abook_quark_vca_email (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_ENCODING (osso_abook_quark_vca_encoding ())
GQuark osso_abook_quark_vca_encoding (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_FBURL (osso_abook_quark_vca_fburl ())
GQuark osso_abook_quark_vca_fburl (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_FN (osso_abook_quark_vca_fn ())
GQuark osso_abook_quark_vca_fn (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_GEO (osso_abook_quark_vca_geo ())
GQuark osso_abook_quark_vca_geo (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_ICSCALENDAR (osso_abook_quark_vca_icscalendar ())
GQuark osso_abook_quark_vca_icscalendar (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_KEY (osso_abook_quark_vca_key ())
GQuark osso_abook_quark_vca_key (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_LABEL (osso_abook_quark_vca_label ())
GQuark osso_abook_quark_vca_label (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_LOGO (osso_abook_quark_vca_logo ())
GQuark osso_abook_quark_vca_logo (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_MAILER (osso_abook_quark_vca_mailer ())
GQuark osso_abook_quark_vca_mailer (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_NICKNAME (osso_abook_quark_vca_nickname ())
GQuark osso_abook_quark_vca_nickname (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_N (osso_abook_quark_vca_n ())
GQuark osso_abook_quark_vca_n (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_NOTE (osso_abook_quark_vca_note ())
GQuark osso_abook_quark_vca_note (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_ORG (osso_abook_quark_vca_org ())
GQuark osso_abook_quark_vca_org (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_PHOTO (osso_abook_quark_vca_photo ())
GQuark osso_abook_quark_vca_photo (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_PRODID (osso_abook_quark_vca_prodid ())
GQuark osso_abook_quark_vca_prodid (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_QUOTEDPRINTABLE (osso_abook_quark_vca_quotedprintable ())
GQuark osso_abook_quark_vca_quotedprintable (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_REV (osso_abook_quark_vca_rev ())
GQuark osso_abook_quark_vca_rev (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_ROLE (osso_abook_quark_vca_role ())
GQuark osso_abook_quark_vca_role (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_TEL (osso_abook_quark_vca_tel ())
GQuark osso_abook_quark_vca_tel (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_TITLE (osso_abook_quark_vca_title ())
GQuark osso_abook_quark_vca_title (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_TYPE (osso_abook_quark_vca_type ())
GQuark osso_abook_quark_vca_type (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_UID (osso_abook_quark_vca_uid ())
GQuark osso_abook_quark_vca_uid (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_URL (osso_abook_quark_vca_url ())
GQuark osso_abook_quark_vca_url (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_VALUE (osso_abook_quark_vca_value ())
GQuark osso_abook_quark_vca_value (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_VERSION (osso_abook_quark_vca_version ())
GQuark osso_abook_quark_vca_version (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_AIM (osso_abook_quark_vca_aim ())
GQuark osso_abook_quark_vca_aim (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_ANNIVERSARY (osso_abook_quark_vca_anniversary ())
GQuark osso_abook_quark_vca_anniversary (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_ASSISTANT (osso_abook_quark_vca_assistant ())
GQuark osso_abook_quark_vca_assistant (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_BIRTHDAY (osso_abook_quark_vca_birthday ())
GQuark osso_abook_quark_vca_birthday (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_BLOG_URL (osso_abook_quark_vca_blog_url ())
GQuark osso_abook_quark_vca_blog_url (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_CALLBACK (osso_abook_quark_vca_callback ())
GQuark osso_abook_quark_vca_callback (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_COMPANY (osso_abook_quark_vca_company ())
GQuark osso_abook_quark_vca_company (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_DEST_CONTACT_UID (osso_abook_quark_vca_dest_contact_uid ())
GQuark osso_abook_quark_vca_dest_contact_uid (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_DEST_EMAIL (osso_abook_quark_vca_dest_email ())
GQuark osso_abook_quark_vca_dest_email (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_DEST_EMAIL_NUM (osso_abook_quark_vca_dest_email_num ())
GQuark osso_abook_quark_vca_dest_email_num (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_DEST_HTML_MAIL (osso_abook_quark_vca_dest_html_mail ())
GQuark osso_abook_quark_vca_dest_html_mail (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_DEST_NAME (osso_abook_quark_vca_dest_name ())
GQuark osso_abook_quark_vca_dest_name (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_DEST_SOURCE_UID (osso_abook_quark_vca_dest_source_uid ())
GQuark osso_abook_quark_vca_dest_source_uid (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_FILE_AS (osso_abook_quark_vca_file_as ())
GQuark osso_abook_quark_vca_file_as (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_ICQ (osso_abook_quark_vca_icq ())
GQuark osso_abook_quark_vca_icq (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_JABBER (osso_abook_quark_vca_jabber ())
GQuark osso_abook_quark_vca_jabber (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_LIST_SHOW_ADDRESSES (osso_abook_quark_vca_list_show_addresses ())
GQuark osso_abook_quark_vca_list_show_addresses (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_LIST (osso_abook_quark_vca_list ())
GQuark osso_abook_quark_vca_list (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_MANAGER (osso_abook_quark_vca_manager ())
GQuark osso_abook_quark_vca_manager (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_MSN (osso_abook_quark_vca_msn ())
GQuark osso_abook_quark_vca_msn (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_RADIO (osso_abook_quark_vca_radio ())
GQuark osso_abook_quark_vca_radio (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_SIP (osso_abook_quark_vca_sip ())
GQuark osso_abook_quark_vca_sip (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_SPOUSE (osso_abook_quark_vca_spouse ())
GQuark osso_abook_quark_vca_spouse (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_TELEX (osso_abook_quark_vca_telex ())
GQuark osso_abook_quark_vca_telex (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_TTYTDD (osso_abook_quark_vca_ttytdd ())
GQuark osso_abook_quark_vca_ttytdd (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_VIDEO_URL (osso_abook_quark_vca_video_url ())
GQuark osso_abook_quark_vca_video_url (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_WANTS_HTML (osso_abook_quark_vca_wants_html ())
GQuark osso_abook_quark_vca_wants_html (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_YAHOO (osso_abook_quark_vca_yahoo ())
GQuark osso_abook_quark_vca_yahoo (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_GADUGADU (osso_abook_quark_vca_gadugadu ())
GQuark osso_abook_quark_vca_gadugadu (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_GROUPWISE (osso_abook_quark_vca_groupwise ())
GQuark osso_abook_quark_vca_groupwise (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_BOOK_URI (osso_abook_quark_vca_book_uri ())
GQuark osso_abook_quark_vca_book_uri (void) G_GNUC_CONST;

#define OSSO_ABOOK_QUARK_VCA_SKYPE (osso_abook_quark_vca_skype ())
GQuark osso_abook_quark_vca_skype (void) G_GNUC_CONST;

G_END_DECLS

#endif /* __OSSO_ABOOK_QUARKS_H__ */
